Entity\Post:
    type: entity
    table: tbl_post
    indexes:
        category_id:
            columns:
                - category_id
    uniqueConstraints:
        slug:
            columns:
                - slug
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
        slug:
            type: string
            nullable: false
            length: 255
            fixed: false
        summary:
            type: text
            nullable: true
            length: 65535
            fixed: false
        content:
            type: text
            nullable: true
            length: null
            fixed: false
        isActive:
            type: boolean
            nullable: true
            default: '1'
            column: is_active
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
